###############################################################################################
#########                              --API Settings--                               #########
###############################################################################################
api-port: 7598
dbhost: 127.0.0.1:3306
dbname: emi
dbuser: emi
dbpass: 'secret'
token: ''