###############################################################################################
#########                              --API Settings--                               #########
###############################################################################################
api-port: 7598
world-folder: 'WORLD-FOLDER-NAME'